kind: Template
apiVersion: v1
metadata:
  name: ${NAME}-template
  labels:
    name: ${NAME}${NAME}-template
    app: ${APP_NAME}
    app-group: ${NAME}
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      generation: 1
      labels:
        app: ${APP_NAME}
        app-group: ${NAME}
        env: ${TAG_NAME}
    spec:
      strategy:
        type: Rolling
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              namespace: ${IMAGE_NAMESPACE}
              name: ${SOURCE_IMAGE_NAME}:${TAG_NAME}
      replicas: 1
      test: false
      selector:
        app: ${APP_NAME}
        app-group: ${NAME}
        env: ${TAG_NAME}
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            app-group: ${NAME}
            env: ${TAG_NAME}
        spec:
          volumes: []
          containers:
            - name: ${NAME}
              ports:
                - containerPort: 5252
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                initialDelaySeconds: 1
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 5252
                timeoutSeconds: 5
              livenessProbe:
                failureThreshold: 3
                initialDelaySeconds: 1
                periodSeconds: 10
                successThreshold: 1
                tcpSocket:
                  port: 5252
                timeoutSeconds: 5
              env:
                - name: ALLURE_DOCKER_PUBLIC_API_URL
                  value: ${ALLURE_DOCKER_PUBLIC_API_URL}
                - name: ALLURE_DOCKER_PUBLIC_API_URL_PREFIX
                  value: ${ALLURE_DOCKER_PUBLIC_API_URL_PREFIX}
              volumeMounts: []
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
  - kind: Route
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        name: ${NAME}
        app: ${APP_NAME}
        app-group: ${NAME}
        env: ${TAG_NAME}
    spec:
      host: ${ALLURE_UI_URL}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${APP_NAME}
        app-group: ${NAME}
        env: ${TAG_NAME}
    spec:
      ports:
        - name: 5252-tcp
          protocol: TCP
          port: 5252
          targetPort: 5252
      selector:
        app: ${APP_NAME}
        app-group: ${NAME}
        env: ${TAG_NAME}
      type: ClusterIP
      sessionAffinity: None
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the OpenShift resources associated to the server instance.
    required: true
    value: allure-ui
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: allure
  - name: ROLE
    displayName: Role
    description: The role of this service within the application - used for Network Policies
    required: true
    value: allure-ui
  - name: NAMESPACE_NAME
    displayName: Namespace Name
    description: The name of the namespace being deployed to.
    required: true
    value: ""
  - name: IMAGE_NAMESPACE
    displayName: Image Namespace
    required: true
    description: The namespace of the OpenShift project containing the imagestream for the application.
    value: ""
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the image to use for this resource.
    required: true
    value: allure-ui
  - name: TAG_NAME
    displayName: Environment TAG name
    description: The TAG name for this environment, e.g., dev, test, prod
    required: true
    value: prod
  - name: ALLURE_UI_URL
    displayName: Allure UI URL
    description: The public domain endpoint for Allure UI. A value will be created by default if not specified.
    required: false
    value: ""
  - name: ALLURE_DOCKER_PUBLIC_API_URL
    displayName: Allure API URL
    description: Allure API URL.
    required: true
    value: ""
  - name: ALLURE_DOCKER_PUBLIC_API_URL_PREFIX
    displayName: Allure API URL Prefix
    description: Allure API URL prefix.
    required: false
    value: ""
  - name: CPU_REQUEST
    displayName: Resources CPU Request
    description: The resources CPU request (in cores) for this build.
    required: true
    value: 100m
  - name: CPU_LIMIT
    displayName: Resources CPU Limit
    description: The resources CPU limit (in cores) for this build.
    required: true
    value: 250m
  - name: MEMORY_REQUEST
    displayName: Resources Memory Request
    description: The resources Memory request (in Mi, Gi, etc) for this build.
    required: true
    value: 128Mi
  - name: MEMORY_LIMIT
    displayName: Resources Memory Limit
    description: The resources Memory limit (in Mi, Gi, etc) for this build.
    required: true
    value: 256Mi
